version: '3'

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - chat-network

  chat-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
    command: npm start
    volumes:
      - .:/usr/src/app
    networks:
      - chat-network

networks:
  chat-network:
    driver: bridge